### ISSUE TITLE
2024-03-19 双周会内容

### ISSUE THREAD

**Issue by lvjing2** [koupleless/koupleless#157]
主题：Serverless 社区双周会
时间：3月19日 周二 19:30 - 20:30 （GMT +8:00）
会议号：90957500367

入会链接：https://meeting.dingtalk.com/j/lzTsT1q9uLC

## 当前业务接入进展
4/5 家企业已接入生产，1家企业完成 poc 待发布线上，2月份新增3家企业 POC 。
阿里妈妈、阿里健康、工商银行、政采云、快手、平安财产保险、中创、司库立方、广州携旅、深圳市共济科技、比特大陆等正在 POC 或开发接入中。

### 待 review pr
- [x] 模块脚手架搭建  @sususama,  差文档、发布工作 @lvjing2 

### Arklet && Runtime
- [x] 支持 spring 2.3.x 2.1.x @gaosaroma  
- [] 适配新版的各个组件 https://github.com/sofastack/sofa-serverless/issues/443，完成 1/4 logback，jdk17 版本adapter 完成验证开发
- [] 组件治理的多版本能力 https://github.com/koupleless/runtime/issues/8 @CodeNoobKing 
- [] samples 的集成测试回归能力 https://github.com/koupleless/runtime/issues/9 @CodeNoobKing 
7. 可观测性增强 https://github.com/sofastack/sofa-serverless/issues/416 
9. 模块支持配置自定义 autoconfiguration 的可行性方案，需要在可自定义与简单易用找到平衡点 https://github.com/sofastack/sofa-serverless/issues/409 
10. [优化自动排包的配置方式](https://github.com/sofastack/sofa-serverless/issues/330) @hustchaya 
11. Arkctl 支持将ark-biz.jar包上传到统一的地方如 oss 仓库 #163  

- [ ] [基座配置 web context path，模块未配置时无法安装模块 ](https://github.com/sofastack/sofa-serverless/issues/320)，无法复现，能正常覆盖安装
- [x]  修复 Samples https://github.com/koupleless/koupleless/issues/156
- [ ] [add sample for pandora boot #155](https://github.com/koupleless/koupleless/issues/155)
- [ ] [add api for list all activated biz #128](https://github.com/koupleless/koupleless/issues/128)
- [ ] [模块安装健康检查 #127](https://github.com/koupleless/koupleless/issues/127) 
- [ ] log4j2 adapter support springboot 2.3.10.RELEASE #91
- [ ] java -jar 的方式启动基座，在jdk17 环境里报错 #159

### ModuleController 
1. 最大不可用数量 @liu-657667   开发 review 中 
2. 支持 helm 方式部署 moduleController  https://github.com/sofastack/sofa-serverless/issues/219

### SOFAArk
迭代规划 @lvjing2  
- [ ] 打包插件依赖 mvn tree时临时文件被覆盖问题：https://github.com/sofastack/sofa-ark/issues/870
- [x] 本地工程无法被扫描 https://github.com/sofastack/sofa-ark/issues/866 
- [ ] web-ark-plugin 插件导致强制委托给基座范围被放大 https://github.com/sofastack/sofa-ark/issues/863

### Arkctl
- [x] Arkctl 支持卸载模块 @CodeNoobKing 

### 质量建设
迭代规划 @gongjiu 
- [ ] 支持 jdk 17 的验证
- [ ] windows环境的验证
- [x] 回归验证迁移到 https://github.com/koupleless/koupleless/blob/main/.github/workflows/samples_formatter_and_unit_test.yml
- [ ] 继续验证完善服务或功能验证

### 产品化配套
- [ ] 用户试用、运营平台能力集成调研：https://github.com/koupleless/koupleless/issues/44
