### ISSUE TITLE
2024-02-20 双周会内容

### ISSUE THREAD

**Issue by lvjing2** [koupleless/koupleless#98]
主题：Serverless 社区双周会
时间：2月20日 周二 19:30 - 20:30 （GMT +8:00）
会议号：90957500367

入会链接：https://meeting.dingtalk.com/j/4SwBZzpwkUS

## 当前业务接入进展
4/5 家企业已接入生产，1家企业完成 poc 待发布线上，1月份新增6家企业 POC 。阿里妈妈、阿里健康、工商银行、政采云、快手、平安财产保险、中创、司库立方、广州携旅、深圳市共济科技、比特大陆等正在 POC 或开发接入中。

### 多 jdk 版本支持方案
![image](https://github.com/koupleless/koupleless/assets/3754074/0c18cb40-3a98-46e3-996d-150ac49787c9)
https://koupleless.io/docs/tutorials/module-development/runtime-compatibility-list/

### 待 review pr
1. 8个 koupleless 待 Review PR 
2. 2个 还放在 SOFAServerless 里的 PR 
- https://github.com/sofastack/sofa-serverless/pull/473
- 模块脚手架搭建  @sususama,  差文档、发布工作 @lvjing2 

### Arklet && Runtime
1. 支持 tomcat 跨模块调用传递  context #33  @qq290584697 @gaosaroma 
2. 支持 spring 2.3.x 2.1.x @lvjing2 
3. 优化跨模块调用序列化问题 @linwanwan
4. 适配新版的各个组件 https://github.com/sofastack/sofa-serverless/issues/443，完成 1/4 logback，jdk17 版本adapter 完成验证开发
- [x] 支持 windows 环境单测
6. 支持 windows 环境的回归校验 ci 流水 https://github.com/sofastack/sofa-serverless/issues/437 待质量配置 ci
- [x] 模块调用基座，支持非 public 方法调用 https://github.com/sofastack/sofa-serverless/issues/442  @qq290584697
7. 可观测性增强 https://github.com/sofastack/sofa-serverless/issues/416 
- [x] 多模块打印日志 https://github.com/koupleless/koupleless/pull/94/files @suntaiming
9. 模块支持配置自定义 autoconfiguration 的可行性方案，需要在可自定义与简单易用找到平衡点 https://github.com/sofastack/sofa-serverless/issues/409 
10. [优化自动排包的配置方式](https://github.com/sofastack/sofa-serverless/issues/330) @gaosaroma 
- [x] [基座配置 web context path，模块未配置时无法安装模块 ](https://github.com/sofastack/sofa-serverless/issues/320)，无法复现，能正常覆盖安装
- [x] 自动部署官网
- [x] samples 的自动代码格式检查与license 校验

### ModuleController 
1. 最大不可用数量 @liu-657667   开发 review 中 
2. 支持 helm 方式部署 moduleController  https://github.com/sofastack/sofa-serverless/issues/219
- [x] 对等部署 @zemingzhu 
- [x] 自动打包发布 modulecontroller 镜像

### SOFAArk
迭代规划 @lvjing2  
- [x] 支持 SpringBoot 3.2 @hustchaya , 待合并
- [x] 支持 netty 0.9.x 版本
- [x] 支持 tomcat 跨模块调用传递  context 

### Arkctl
迭代规划 @CodeNoobKing 
- [x] Arkctl 支持卸载模块 @CodeNoobKing 

### 质量建设
迭代规划 @gongjiu 
- [ ] 支持 jdk 17 的验证
- [ ] windows环境的验证
- [ ] 回归验证迁移到 https://github.com/koupleless/koupleless/blob/main/.github/workflows/samples_formatter_and_unit_test.yml
- [ ] 继续验证完善服务或功能验证

### 产品化配套
- [x] Koupleless 答疑机器人调研与方案选型：https://github.com/koupleless/koupleless/issues/39 （每周会定期更新知识库）
- [x] Koupleless 官网搜索引擎优化：https://github.com/koupleless/koupleless/issues/40
- [ ] 用户试用、运营平台能力集成调研：https://github.com/koupleless/koupleless/issues/44
